### ISSUE TITLE
System.out.println with class named "System"

### ISSUE THREAD

**Issue by saelo** [mj3-16/mjtest#30]
The testcase [identifier_system_in_scope6.mj](https://github.com/mj3-16/mjtest/blob/master/tests/semantic/identifier_system_in_scope6.mj) has been marked valid in https://github.com/mj3-16/mjtest/commit/803be083b2a9bc562d5c9c5350f4348bb4a7c17e

The "Sprachbericht" says the following: 

> Ist kein Bezeichner System bekannt, so erzeugt dieser Ausdruck einen Aufruf der System.out.println-Funktion in der Standardbibliothek.

There is no word about namespaces here, so I would assume that in this case an identifier `System` is available (as a class), thus the test should be invalid.

Opinions?

**Comment by parttimenerd** [comment]
See: https://github.com/mj3-16/mjtest/pull/28

I've written a mail to our supervisors.

**Comment by suluke** [comment]
It should be noted that having the call to the stdlib collide with class names is essentially prohibiting classes from being named `System` in the first place. With this rule it is impossible to achieve a scope in which the stdlib function can be called. Since MiniJava programs are essentially useless without the `System.out.println` function, I don't see why anyone would ever want to call a class `System`.
I am not in favor of the alternative, since I strongly prefer keeping as much of the original Java semantics as possible. I just want to make sure everyone is aware of the consequences.

Fun fact: Assuming the OP's interpretation, one could write an optimization pass that reduces Minijava programs to empty programs if the following conditions are met:
* A class called `System` is defined in the code
* Both the CFG and the Callgraph are known not to contain any cycles

**Comment by parttimenerd** [comment]
One of our advisor answered my question about the validity of the program:

> Hi Johannes,

> ich habe gerade mal schnell den Referenz-Compiler drauf geworfen und der lehnt das Programm nicht ab.

> Grüße,
> Sebastian 

Therefore it should be the safest to just accept the program and discuss it in the meeting tomorrow.

**Comment by CodeMonkey90** [comment]
> There is no word about namespaces here, so I would assume that in this case an identifier System is available (as a class)

I'd say the test is correct since we don't have static access at all, and therefore class names are completely irrelevant for member lookup.

**Comment by sgraf812** [comment]
I'll again refer to #28. The fact that we could resolve this is no reason that we should.

The only reason this test stays valid is that the reference compiler does, which is rather debatable.

**Comment by parttimenerd** [comment]
The final decision in todays meeting: It should be valid.
